apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ynajw12hw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ynajw12hw-go 
  name: ynajw12hw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ynajw12hw-go 
